### ISSUE TITLE
Add time interval option

### ISSUE THREAD

**Issue by ghtmtt** [Mergifyio/mergify-engine#335] opened 2019-01-16 11:43 UTC
Besides all the rules and conditions it would be very useful to automatic merge the PR after a certain amount of time

**Comment by gmartinez-anchor** [comment] 2020-06-19 13:10
We are also interested in a condition to check for the age of the PR.

The plan is to combine with any desired action such as add a message, close, etc.

**Comment by gmartinez-anchor** [comment] 2020-06-19 13:23
Possible duplicate or related? https://github.com/Mergifyio/mergify-engine/issues/349

**Comment by jd** [comment] 2020-06-19 13:43
Duplicate of https://github.com/Mergifyio/mergify-engine/issues/275

**Closed by jd** 2020-06-19 13:43 UTC
Labels: enhancement
