### ISSUE TITLE
Action: leave comment

### ISSUE THREAD

**Issue by amihaiemil** [Mergifyio/mergify-engine#315] opened 2018-12-06 08:42 UTC
Is it possible to instruct mergify to leave a comment after all checks are passed, rather than performing the actual merge? 

I am using [Rultor](http://www.rultor.com/) for merge/deploy/release operations and I already have everything configured. The difference is that Rultor doesn't work automatically, it needs a command before doing anything. 

So, in order to not grant ``write`` access to mergify as well, I would just like mergify to leave a comment for Rultor when it knows that the PR can be merged.

For instance, [here is](https://github.com/amihaiemil/docker-java-api/pull/190#issuecomment-441539174) how Rultor merges a PR. Instead of me giving the command, it would be Mergify doing it :)

**Comment by jd** [comment] 2018-12-06 09:44
Duplicate of https://github.com/Mergifyio/mergify-engine/issues/286

**Closed by jd** 2018-12-06 09:44 UTC
