### ISSUE TITLE
Allow to merge with classic `git rebase`

### ISSUE THREAD

**Issue by jd** [Mergifyio/mergify-engine#243] opened 2018-10-12 08:45 UTC
GitHub `rebase` merge is different than `git rebase` as it always rewrite the commit, which might be a pain. This is described here https://help.github.com/articles/about-merge-methods-on-github/:

> The rebase and merge behavior on GitHub deviates slightly from git rebase.
> Rebase and merge on GitHub will always update the committer information and
> create new commit SHAs, whereas git rebase outside of GitHub does not
> change the committer information when the rebase happens on top of an
> ancestor commit.

It'd be nice to have a way to fast-forward merge pull requests that don't need to be rebased, rather than use GitHub rebase feature which rewrites the commit anyhow.

**Comment by geekflyer** [comment] 2018-10-12 08:52
Here's somewhat of the equivalent that github does (it's not exactly the same since github actually also edits the commit message to add some metadata about the PR, but it demonstrates the issue):

```
git rebase master --force
```

This will rewrite all commits in the feature branch (that are not on master), even if they are already all based on master and technically the rebase wasn't necessary.

**Comment by Elv13** [comment] 2018-10-15 23:31
(Semi duplicate of #115)

Please also add the `git rebase`+`git merge` version to prevent the commit graph to tangle. It's not only cosmetic, it also helps to display all commits from a pull request using standard and simple git commands instead of convoluted one-liners or external scripts/programs. This is of great value.

**Comment by sileht** [comment] 2019-05-19 19:18
This can be done now with: 

```
merge:
    method: merge
    strict: smart
    strict_method: rebase
```

Mergify will rebase the PR automatically before merging it. This is the equivalent to

```
git rebase origin/master
git merge --no-ff ...
```

**Closed** 2019-05-19 19:19 UTC
Labels: enhancement
