### ISSUE TITLE
Using age of the last commit as a condition

### ISSUE THREAD

**Issue by chrisgorgo** [Mergifyio/mergify-engine#349] opened 2019-02-14 22:00 UTC
I am running an open source community project where we would like to make sure that each PR will be open for enough time for people to see it. Thus even if a PR has the requested number of positive reviews it should not be merged before x number of days since the last commit. Is such rule possible in mergify?

**Comment by aldesantis** [comment] 2020-05-22 12:52
Same here! In https://github.com/solidusio/solidus, we require 2 reviews from the core team AND for a PR to have been open for 24 hours before merging it.

**Comment by jd** [comment] 2020-06-19 13:42
Duplicate of https://github.com/Mergifyio/mergify-engine/issues/335

**Closed** 2020-06-19 13:43 UTC
Labels: duplicate, enhancement
