### ISSUE TITLE
if cherry-pick/merge/rebase fail and the message contains <!--, some part are hidden

### ISSUE THREAD

**Issue by blindpirate** [Mergifyio/mergify-engine#1529] opened 2020-10-29 01:57 UTC
Mergify.yml: https://github.com/gradle/gradle/blob/51cc80b5fb1e7e0d202138a13d031985f32de091/.github/mergify.yml

When conditions were met, I expected mergify to update current branch, but it fails with:

```
Base branch update has failed
First, rewinding head to replay your work on top of it...
Applying: Create mergify.yml (#14998)
.git/rebase-apply/patch:132: trailing whitespace.
```

https://github.com/gradle/gradle/pull/14985/checks?check_run_id=1324228249

![image](https://user-images.githubusercontent.com/12689835/97516010-313cf280-19cd-11eb-9e1b-f74e7d7b1e7c.png)

What shall I do now?

**Comment by sileht** [comment] 2020-10-29 06:36
This is reporting issue, the complete message is:

```
First, rewinding head to replay your work on top of it...
Applying: Create mergify.yml (#14998)
.git/rebase-apply/patch:132: trailing whitespace.
<!--- 
.git/rebase-apply/patch:133: trailing whitespace.
Please follow the instructions below. 
.git/rebase-apply/patch:134: trailing whitespace.
We receive dozens of issues every week, so to stay productive, we will close issues that don\'t provide enough information. 
.git/rebase-apply/patch:152: trailing whitespace.
### Steps to Reproduce 
.git/rebase-apply/patch:172: trailing whitespace.
<!--- 
warning: squelched 2264 whitespace errors
warning: 2269 lines add whitespace errors.
warning: Cannot merge binary files: gradle/verification-keyring.gpg (HEAD vs. Create mergify.yml (#14998))
Using index info to reconstruct a base tree...
Falling back to patching base and 3-way merge...
Auto-merging subprojects/tooling-api/src/testFixtures/groovy/org/gradle/integtests/tooling/fixture/ToolingApiSpecification.groovy
CONFLICT (add/add): Merge conflict in subprojects/tooling-api/src/testFixtures/groovy/org/gradle/integtests/tooling/fixture/ToolingApiSpecification.groovy
Auto-merging subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r64/DaemonReuseCrossVersionSpec.groovy
CONFLICT (add/add): Merge conflict in subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r64/DaemonReuseCrossVersionSpec.groovy
Auto-merging subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r22/ClientShutdownCrossVersionSpec.groovy
CONFLICT (add/add): Merge conflict in subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r22/ClientShutdownCrossVersionSpec.groovy
Auto-merging subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/BuildScanPluginSmokeTest.groovy
CONFLICT (add/add): Merge conflict in subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/BuildScanPluginSmokeTest.groovy
Auto-merging subprojects/kotlin-dsl/src/test/resources/org/gradle/kotlin/dsl/accessors/tasks/PrintAccessors-expected-output.txt
CONFLICT (add/add): Merge conflict in subprojects/kotlin-dsl/src/test/resources/org/gradle/kotlin/dsl/accessors/tasks/PrintAccessors-expected-output.txt
Auto-merging subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/delegates/DependencyHandlerDelegate.kt
CONFLICT (add/add): Merge conflict in subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/delegates/DependencyHandlerDelegate.kt
Auto-merging subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/bytecode/KotlinMetadata.kt
CONFLICT (add/add): Merge conflict in subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/bytecode/KotlinMetadata.kt
Auto-merging subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/accessors/runtime/Runtime.kt
CONFLICT (add/add): Merge conflict in subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/accessors/runtime/Runtime.kt
Auto-merging subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/accessors/GradleType.kt
CONFLICT (add/add): Merge conflict in subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/accessors/GradleType.kt
Auto-merging subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/accessors/AccessorsClassPath.kt
CONFLICT (add/add): Merge conflict in subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/accessors/AccessorsClassPath.kt
Auto-merging subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/accessors/AccessorFragments.kt
CONFLICT (add/add): Merge conflict in subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/accessors/AccessorFragments.kt
Auto-merging subprojects/kotlin-dsl-tooling-builders/src/main/kotlin/org/gradle/kotlin/dsl/tooling/builders/KotlinBuildScriptModelBuilder.kt
CONFLICT (add/add): Merge conflict in subprojects/kotlin-dsl-tooling-builders/src/main/kotlin/org/gradle/kotlin/dsl/tooling/builders/KotlinBuildScriptModelBuilder.kt
Auto-merging subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/FeaturePreviewsFixture.groovy
CONFLICT (add/add): Merge conflict in subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/FeaturePreviewsFixture.groovy
Auto-merging subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractDependencyResolutionTest.groovy
CONFLICT (add/add): Merge conflict in subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractDependencyResolutionTest.groovy
Auto-merging subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/DistributionIntegrationSpec.groovy
CONFLICT (add/add): Merge conflict in subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/DistributionIntegrationSpec.groovy
Auto-merging subprojects/distributions-dependencies/build.gradle.kts
CONFLICT (add/add): Merge conflict in subprojects/distributions-dependencies/build.gradle.kts
Auto-merging subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/dsl/dependencies/DefaultDependencyHandlerTest.groovy
CONFLICT (add/add): Merge conflict in subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/dsl/dependencies/DefaultDependencyHandlerTest.groovy
Auto-merging subprojects/dependency-management/src/main/java/org/gradle/internal/management/DefaultDependencyResolutionManagement.java
CONFLICT (add/add): Merge conflict in subprojects/dependency-management/src/main/java/org/gradle/internal/management/DefaultDependencyResolutionManagement.java
Auto-merging subprojects/dependency-management/src/main/java/org/gradle/api/internal/notations/DependencyNotationParser.java
CONFLICT (add/add): Merge conflict in subprojects/dependency-management/src/main/java/org/gradle/api/internal/notations/DependencyNotationParser.java
Auto-merging subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dsl/dependencies/DefaultDependencyHandler.java
CONFLICT (add/add): Merge conflict in subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dsl/dependencies/DefaultDependencyHandler.java
Auto-merging subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dependencies/DefaultMutableVersionConstraint.java
CONFLICT (add/add): Merge conflict in subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dependencies/DefaultMutableVersionConstraint.java
Auto-merging subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dependencies/DefaultImmutableVersionConstraint.java
CONFLICT (add/add): Merge conflict in subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dependencies/DefaultImmutableVersionConstraint.java
Auto-merging subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dependencies/DefaultExternalModuleDependency.java
CONFLICT (add/add): Merge conflict in subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dependencies/DefaultExternalModuleDependency.java
Auto-merging subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dependencies/AbstractExternalModuleDependency.java
CONFLICT (add/add): Merge conflict in subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dependencies/AbstractExternalModuleDependency.java
Auto-merging subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DependencyServices.java
CONFLICT (add/add): Merge conflict in subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DependencyServices.java
Auto-merging subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DependencyManagementGradleUserHomeScopeServices.java
CONFLICT (add/add): Merge conflict in subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DependencyManagementGradleUserHomeScopeServices.java
Auto-merging subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DependencyManagementBuildScopeServices.java
CONFLICT (add/add): Merge conflict in subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DependencyManagementBuildScopeServices.java
Auto-merging subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DefaultDependencyManagementServices.java
CONFLICT (add/add): Merge conflict in subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DefaultDependencyManagementServices.java
Auto-merging subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/rules/ComponentMetadataRulesInSettingsIntegrationTest.groovy
CONFLICT (add/add): Merge conflict in subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/rules/ComponentMetadataRulesInSettingsIntegrationTest.groovy
Auto-merging subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/RepositoriesDeclaredInSettingsIntegrationTest.groovy
CONFLICT (add/add): Merge conflict in subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/RepositoriesDeclaredInSettingsIntegrationTest.groovy
Auto-merging subprojects/core/src/testFixtures/groovy/org/gradle/test/fixtures/AbstractProjectBuilderSpec.groovy
CONFLICT (add/add): Merge conflict in subprojects/core/src/testFixtures/groovy/org/gradle/test/fixtures/AbstractProjectBuilderSpec.groovy
Auto-merging subprojects/core/src/test/groovy/org/gradle/initialization/SettingsFactoryTest.groovy
CONFLICT (add/add): Merge conflict in subprojects/core/src/test/groovy/org/gradle/initialization/SettingsFactoryTest.groovy
Auto-merging subprojects/core/src/test/groovy/org/gradle/initialization/DefaultSettingsTest.groovy
CONFLICT (add/add): Merge conflict in subprojects/core/src/test/groovy/org/gradle/initialization/DefaultSettingsTest.groovy
Auto-merging subprojects/core/src/test/groovy/org/gradle/execution/plan/DefaultExecutionPlanParallelTest.groovy
CONFLICT (add/add): Merge conflict in subprojects/core/src/test/groovy/org/gradle/execution/plan/DefaultExecutionPlanParallelTest.groovy
Auto-merging subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/execution/ResolveTaskExecutionModeExecuterTest.groovy
CONFLICT (add/add): Merge conflict in subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/execution/ResolveTaskExecutionModeExecuterTest.groovy
Auto-merging subprojects/core/src/main/java/org/gradle/plugin/management/internal/autoapply/AutoAppliedGradleEnterprisePlugin.java
CONFLICT (add/add): Merge conflict in subprojects/core/src/main/java/org/gradle/plugin/management/internal/autoapply/AutoAppliedGradleEnterprisePlugin.java
Auto-merging subprojects/core/src/main/java/org/gradle/internal/management/DependencyResolutionManagementInternal.java
CONFLICT (add/add): Merge conflict in subprojects/core/src/main/java/org/gradle/internal/management/DependencyResolutionManagementInternal.java
Auto-merging subprojects/core/src/main/java/org/gradle/internal/composite/ChildBuildRegisteringSettingsLoader.java
CONFLICT (add/add): Merge conflict in subprojects/core/src/main/java/org/gradle/internal/composite/ChildBuildRegisteringSettingsLoader.java
Auto-merging subprojects/core/src/main/java/org/gradle/initialization/SettingsFactory.java
CONFLICT (add/add): Merge conflict in subprojects/core/src/main/java/org/gradle/initialization/SettingsFactory.java
Auto-merging subprojects/core/src/main/java/org/gradle/initialization/DefaultSettings.java
CONFLICT (add/add): Merge conflict in subprojects/core/src/main/java/org/gradle/initialization/DefaultSettings.java
Auto-merging subprojects/core/src/main/java/org/gradle/execution/plan/TaskNodeFactory.java
CONFLICT (add/add): Merge conflict in subprojects/core/src/main/java/org/gradle/execution/plan/TaskNodeFactory.java
Auto-merging subprojects/core/src/main/java/org/gradle/execution/plan/LocalTaskNodeExecutor.java
CONFLICT (add/add): Merge conflict in subprojects/core/src/main/java/org/gradle/execution/plan/LocalTaskNodeExecutor.java
Auto-merging subprojects/core/src/main/java/org/gradle/execution/plan/LocalTaskNode.java
CONFLICT (add/add): Merge conflict in subprojects/core/src/main/java/org/gradle/execution/plan/LocalTaskNode.java
Auto-merging subprojects/core/src/main/java/org/gradle/execution/ProjectExecutionServices.java
CONFLICT (add/add): Merge conflict in subprojects/core/src/main/java/org/gradle/execution/ProjectExecutionServices.java
Auto-merging subprojects/core/src/main/java/org/gradle/configuration/BuildTreePreparingProjectsPreparer.java
CONFLICT (add/add): Merge conflict in subprojects/core/src/main/java/org/gradle/configuration/BuildTreePreparingProjectsPreparer.java
Auto-merging subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/GetOutputFilesVisitor.java
CONFLICT (add/add): Merge conflict in subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/GetOutputFilesVisitor.java
Auto-merging subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/DefaultTaskProperties.java
CONFLICT (add/add): Merge conflict in subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/DefaultTaskProperties.java
Auto-merging subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/ResolveTaskExecutionModeExecuter.java
CONFLICT (add/add): Merge conflict in subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/ResolveTaskExecutionModeExecuter.java
Auto-merging subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/DefaultTaskExecutionContext.java
CONFLICT (add/add): Merge conflict in subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/DefaultTaskExecutionContext.java
Auto-merging subprojects/core/src/main/java/org/gradle/api/internal/tasks/TaskStateInternal.java
CONFLICT (add/add): Merge conflict in subprojects/core/src/main/java/org/gradle/api/internal/tasks/TaskStateInternal.java
Auto-merging subprojects/core/src/main/java/org/gradle/api/internal/tasks/TaskExecutionContext.java
CONFLICT (add/add): Merge conflict in subprojects/core/src/main/java/org/gradle/api/internal/tasks/TaskExecutionContext.java
Auto-merging subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultTaskOutputs.java
CONFLICT (add/add): Merge conflict in subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultTaskOutputs.java
Auto-merging subprojects/core/src/main/java/org/gradle/api/internal/project/ProjectFactory.java
CONFLICT (add/add): Merge conflict in subprojects/core/src/main/java/org/gradle/api/internal/project/ProjectFactory.java
Auto-merging subprojects/core/src/main/java/org/gradle/api/internal/FeaturePreviews.java
CONFLICT (add/add): Merge conflict in subprojects/core/src/main/java/org/gradle/api/internal/FeaturePreviews.java
Auto-merging subprojects/core/src/main/java/org/gradle/api/internal/DefaultClassPathProvider.java
CONFLICT (add/add): Merge conflict in subprojects/core/src/main/java/org/gradle/api/internal/DefaultClassPathProvider.java
Auto-merging subprojects/core/src/integTest/groovy/org/gradle/api/tasks/TaskParametersIntegrationTest.groovy
CONFLICT (add/add): Merge conflict in subprojects/core/src/integTest/groovy/org/gradle/api/tasks/TaskParametersIntegrationTest.groovy
Auto-merging subprojects/core/build.gradle.kts
CONFLICT (add/add): Merge conflict in subprojects/core/build.gradle.kts
Auto-merging subprojects/core-api/src/main/java/org/gradle/api/initialization/resolve/DependencyResolutionManagement.java
CONFLICT (add/add): Merge conflict in subprojects/core-api/src/main/java/org/gradle/api/initialization/resolve/DependencyResolutionManagement.java
Auto-merging subprojects/core-api/src/main/java/org/gradle/api/artifacts/dsl/DependencyHandler.java
CONFLICT (add/add): Merge conflict in subprojects/core-api/src/main/java/org/gradle/api/artifacts/dsl/DependencyHandler.java
Auto-merging subprojects/composite-builds/src/main/java/org/gradle/composite/internal/DefaultIncludedBuildRegistry.java
CONFLICT (add/add): Merge conflict in subprojects/composite-builds/src/main/java/org/gradle/composite/internal/DefaultIncludedBuildRegistry.java
Auto-merging subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/IncludedBuildValidationIntegrationTest.groovy
CONFLICT (add/add): Merge conflict in subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/IncludedBuildValidationIntegrationTest.groovy
Auto-merging subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/CompositeBuildNestingIntegrationTest.groovy
CONFLICT (add/add): Merge conflict in subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/CompositeBuildNestingIntegrationTest.groovy
Auto-merging settings.gradle.kts
CONFLICT (add/add): Merge conflict in settings.gradle.kts
Auto-merging released-versions.json
CONFLICT (add/add): Merge conflict in released-versions.json
Auto-merging gradle/verification-metadata.xml
CONFLICT (add/add): Merge conflict in gradle/verification-metadata.xml
Auto-merging gradle/verification-keyring.gpg
CONFLICT (add/add): Merge conflict in gradle/verification-keyring.gpg
Auto-merging buildSrc/subprojects/jvm/src/main/kotlin/gradlebuild.api-parameter-names-index.gradle.kts
CONFLICT (add/add): Merge conflict in buildSrc/subprojects/jvm/src/main/kotlin/gradlebuild.api-parameter-names-index.gradle.kts
Auto-merging buildSrc/subprojects/dependency-modules/src/main/kotlin/gradlebuild/modules/extension/ExternalModulesExtension.kt
CONFLICT (add/add): Merge conflict in buildSrc/subprojects/dependency-modules/src/main/kotlin/gradlebuild/modules/extension/ExternalModulesExtension.kt
Auto-merging buildSrc/subprojects/build-platform/build.gradle.kts
CONFLICT (add/add): Merge conflict in buildSrc/subprojects/build-platform/build.gradle.kts
Auto-merging .github/mergify.yml
CONFLICT (add/add): Merge conflict in .github/mergify.yml
error: Failed to merge in the changes.
Patch failed at 0001 Create mergify.yml (#14998)
Use \'git am --show-current-patch\' to see the failed patch

Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
```

**Comment by blindpirate** [comment] 2020-10-29 06:38
So is there anything I can do/workaround this issue?

**Comment by sileht** [comment] 2020-10-29 06:48
On our side, we will just ensure that Github doesn't hide some part of the message. But we can't fix the conflict itself.

**Comment by blindpirate** [comment] 2020-10-29 06:55
No I think there's something not right. If you take a deep look into that PR and the error message, you can see something fishy.

1. I was trying to instruct Mergify to rebase base branch (`master`) in this PR: https://github.com/gradle/gradle/pull/14985 This PR has only one changed file, but your error log says there're many CONFLICT. I try to manually rebase this PR, no conflicts at all:

```
# zhb @ bs-MacBook-Pro-2 in ~/Projects/gradle on git:blindpirate/check-cleanup-step o [14:50:53]
$ git rebase master
First, rewinding head to replay your work on top of it...
Applying: Not fail the build if cleanup step finds leftover test files
```

2. The error says: 

```
First, rewinding head to replay your work on top of it...
Applying: Create mergify.yml (#14998)
```

If you take a look at https://github.com/gradle/gradle/pull/14998 you can see that PR only contains added mergify.yml, nothing else. It can't conflict with that many files.

Am I misunderstanding something?

**Comment by sileht** [comment] 2020-10-29 07:17
Mergify use shallow `git clone` to rebase/update branch, it can be related to this, I will take a look closer.

**Comment by blindpirate** [comment] 2020-10-29 07:18
I don't understand why shallow clone can cause unrelated files to be conflict....

**Comment by sileht** [comment] 2020-10-29 07:30
Here what mergify have done for this PR:

```
git init
git remote set-url origin https://github.com/gradle/gradle.git
git remote set-url upstream https://github.com/gradle/gradle.git
git fetch --quiet --depth=1 origin blindpirate/check-cleanup-step
git checkout -b blindpirate/check-cleanup-step origin/blindpirate/check-cleanup-step

D=$(git log --format="%cI")
git fetch upstream master --shallow-since="$D"
git rebase upstream/master
```

And it results in the same conflict. I think we didn't fetch enough data, that why it fails.

**Comment by blindpirate** [comment] 2020-10-29 07:40
Thanks @sileht ! `--depth=1` seems not enough, I think at least 

```
git fetch --shallow-since=<base ref commit date>
```

according to this post: https://stackoverflow.com/questions/27059840/how-to-fetch-enough-commits-to-do-a-merge-in-a-shallow-clone

**Comment by blindpirate** [comment] 2020-10-29 07:41
I'll fallback to `merge` method for now, are you going to fix this in recent release (like next milestone)?

**Comment by sileht** [comment] 2020-10-29 07:42
Thanks for the pointer we will improve our heuristic to detect where branch diverge.

I cannot give eta, but it will be fixed for sure

**Comment by sileht** [comment] 2020-10-29 09:35
I have opened another issue for this, since the first issue will be merged soon.

**Closed** 2020-10-30 13:11 UTC

**Comment by San1212** [comment] 2020-11-18 14:44
#1585 
Duplicate of @#
