### ISSUE TITLE
Mergify backport picking up additional commits

### ISSUE THREAD

**Issue by howardjohn** [Mergifyio/mergify-engine#426] opened 2019-06-05 17:58 UTC
Example PR: https://github.com/istio/istio/pull/14565

It pulled in 3 commits when there should only be 1. We don't use mergify for the actual merging which may be related. Additionally the original PR had 3 commits which got squashed, so maybe thats why it pulled 3 commits in?

**Comment by sileht** [comment] 2019-06-05 18:09
Yes Mergify copy commits of original pull request and not what was merged.

**Comment by howardjohn** [comment] 2019-06-05 18:11
That isn't what happened here though. It pulled one change as expected  "Apply locality overrides in bootstrap" and two unrelated changes from different PRs 

https://github.com/istio/istio/pull/14565/commits

**Comment by sileht** [comment] 2019-06-05 18:14
Oh I see the 3 commits are not the good one.

**Comment by sileht** [comment] 2019-06-05 18:17
That's a duplicate of https://github.com/Mergifyio/mergify-engine/issues/359

**Closed** 2019-06-06 16:52 UTC
Labels: duplicate
