### ISSUE TITLE
Deleted branch for PR doesn't exit queue

### ISSUE THREAD

**Issue by thejcannon** [Mergifyio/mergify-engine#5113] opened 2024-05-01 19:28 UTC
## Steps to Reproduce the Problem

  1. Make branch and open PR
  2. Enqueue the PR
  3. Delete the branch on origin
    - This closes the GH PR 
  5. Mergify will keep the closed PR at the head of the queue 

## Expected Behavior

The PR is dequeued

## Actual Behavior

The PR is forever the head of the queue

## Specifications

  - Pull Request URL: N/A (self-hosted)
  - Mergify Config URL: N/A (I'm using a blank config)

**Comment by thejcannon** [comment] 2024-05-01 19:29
<img width="908" alt="Screenshot 2024-05-01 at 2 29 32 PM" src="https://github.com/Mergifyio/mergify/assets/3956745/1bbc118b-1ef8-49ab-a1d7-91f053c6c330">

**Comment by thejcannon** [comment] 2024-05-01 20:03
FWIW I've also seen Mergify handle this correctly. So I suspect now it must be a race.

**Comment by jd** [comment] 2024-05-01 20:23
👋  @thejcannon 
We've opened a ticket internally and we'll look into it ASAP!

**Comment by DouglasBlackwood** [comment] 2024-05-06 09:30
Hi @thejcannon 

I ran several tests but I can't reproduce the bug. GitHub sends a "pull request closed" event and Mergify dequeues the pull request as expected.

How often do you notice this bug? Did you find any common pattern?

**Comment by thejcannon** [comment] 2024-05-07 11:21
No, seemed like a blip really.

One thing I vaguely remember from bors is that GitHub doesn't retry webhooks. So if you blink and miss it you're SOL. I can go see if GitHub still has the webhooks log and see if any weren't responded to.

Otherwise feel free to close as not reproducible

**Comment by jd** [comment] 2024-05-07 11:47
That'd be a good check. I'll close it in the meantime but feel free to reopen if you see this happening again.

**Closed as not planned by jd** 2024-05-07 11:47 UTC

**Comment by thejcannon** [comment] 2024-05-07 23:47
Ah looks like GitHub only stored recent deliveries for the last day-or-so 😭
